---
- name: Create slapd db config backups
  environment: "{{ working_env }}"
  shell: |
    "{{ slapcat_path }} -n {{ item[0] }} -F {{ item[1] }} -l {{ backup_dir_path }}/{{ item[2] }}.ldif > {{ backup_dir_path }}/{{ item[2] }}.out 2> {{ backup_dir_path }}/{{ item[2] }}.err"
  with_items: "{{ backup_targets_config }}"
  tags:
    - backup:ldap

- name: Create slapd db data backups
  environment: "{{ working_env }}"
  shell: |
    "{{ slapcat_path }} -n {{ item[0] }} -F {{ item[1] }} -l {{ backup_dir_path }}/{{ item[2] }}.ldif > {{ backup_dir_path }}/{{ item[2] }}.out 2> {{ backup_dir_path }}/{{ item[2] }}.err"
  with_items: "{{ backup_targets_data }}"
  tags:
    - backup:ldap

- name: Zip data
  environment: "{{ working_env }}"
  shell: |
    zip {{ backup_dir_path }}/{{ item[2] }}.$(date -d "today" +"%Y%m%d%H%M").zip {{ backup_dir_path }}/{{ item[2] }}.ldif > {{ backup_dir_path }}/zip.out 2> {{ backup_dir_path }}/zip.err
  with_items: "{{ backup_targets_data }}"
  tags:
    - backup:zip

- name: Cleanup old files
  environment: "{{ working_env }}"
  shell: |
    rm -f {{ backup_dir_path }}/{{ item[2] }}.ldif
    find {{ backup_dir_path}} -name "*.zip" -mtime +14 | xargs rm -rf 
  with_items: "{{ backup_targets_data }}"
  tags:
    - backup:cleanup
