---
- name: Create slapd db config backups
  environment: "{{ working_env }}"
  shell: |
    "{{ slapcat_path }}" -n "{{ item.index }}" -F "{{ item.config_path }}" -l "{{ backup_dir_path_ldif }}/{{ item.backup_name }}.ldif" > "{{ backup_dir_path }}/{{ item.backup_name }}.out" 2> "{{ backup_dir_path }}/{{ item.backup_name }}.err"
  with_items: "{{ backup_targets_config }}"
  tags:
    - backup:ldap

- name: Create slapd db data backups
  environment: "{{ working_env }}"
  shell: |
    "{{ slapcat_path }}" -n "{{ item.index }}" -F "{{ item.config_path }}" -l "{{ backup_dir_path_ldif }}/{{ item.backup_name }}.ldif" > "{{ backup_dir_path }}/{{ item.backup_name }}.out" 2> "{{ backup_dir_path }}/{{ item.backup_name }}.err"
  with_items: "{{ backup_targets_data }}"
  tags:
    - backup:ldap

- name: Zip data
  environment: "{{ working_env }}"
  shell: |
    /bin/zip {{ backup_dir_path_ldif }}/{{ item.backup_name }}$(/bin/date -d 'today' +'%Y%m%d%H%M').zip {{ backup_dir_path_ldif }}/{{ item.backup_name }}.ldif > {{ backup_dir_path }}/zip.out 2> {{ backup_dir_path }}/zip.err
  with_items: "{{ backup_targets_data }}"
  tags:
    - backup:zip

- name: Cleanup old files
  environment: "{{ working_env }}"
  shell: |
    /bin/rm -f {{ backup_dir_path_ldif }}/{{ item.backup_name }}.ldif
    /bin/find {{ backup_dir_path_ldif }} -name "*.zip" -mtime +14 | /bin/xargs /bin/rm -rf 
  with_items: "{{ backup_targets_data }}"
  tags:
    - backup:cleanup
