openldap_install_dir: /appl/openldap/
cyrus_sasl_install_dir: /appl/openldap/
unixodbc_install_dir: /appl/openldap/
openssl_install_dir: /appl/openldap/
backup_dir_path: /appl/backup/
backup_dir_path_ldif: /appl/backup/openldap
slapcat_path: "{{ openldap_install_dir }}/sbin/slapcat"
backup_targets_config:
  - {index: "0", config_path: "/appl/openldap/etc/openldap/slapd.d", backup_name: "slapd.d"}
  #- {index: "0", config_path: "/appl/openldap/etc/openldap/bindproxy.d", backup_name: "bindproxy.d"}
backup_targets_data:
  - {index: "1", config_path: "/appl/openldap/etc/openldap/slapd.d", backup_name: "data"}
working_env:
  PATH: "$PATH:$HOME/bin"
  LD_LIBRARY_PATH: "{{ openssl_install_dir }}/lib:{{ cyrus_sasl_install_dir }}/lib:{{ unixodbc_install_dir }}/lib:{{ openldap_install_dir }}/lib:$LD_LIBRARY_PATH"
  CC: gcc
  CFLAGS: -O -g
  CPPFLAGS: -I{{ openssl_install_dir }}/include -I{{ openssl_install_dir }}/include/openssl -I{{ unixodbc_install_dir }}/include -I{{ cyrus_sasl_install_dir }}/include -I{{ openldap_install_dir }}/include -I/usr/include
  LDFLAGS: -L{{ openssl_install_dir }}/lib -L{{ unixodbc_install_dir }}/lib -L{{ cyrus_sasl_install_dir }}/lib -L{{ openldap_install_dir }}/lib -L/usr/lib
  LIBS: -lpthread -ldl
  LDAP_HOME: "{{ openldap_install_dir }}"
